// The automorphisms of a graph form a finite group. A "base" is a small set of
// generators of it: the user only has to decide what the generators become in
// the rhs, everything else is obtained by composition.
//
// A morphism is { nodeMap, edgeMap }.

const entries = (o) => Object.keys(o || {}).sort().map((k) => k + ':' + o[k]).join(',')

class Base {
  // morphisms: all the automorphisms of a graph (the identity included)
  constructor (morphisms) {
    this.base = []
    this.saturation = []
    this.generateBase(morphisms)
  }

  static key (m) {
    return entries(m.nodeMap) + '|' + entries(m.edgeMap)
  }

  // "first, then second"
  static then (first, second) {
    const nodeMap = {}
    const edgeMap = {}
    for (const n in first.nodeMap) nodeMap[n] = second.nodeMap[first.nodeMap[n]]
    for (const e in first.edgeMap) edgeMap[e] = second.edgeMap[first.edgeMap[e]]
    return { nodeMap, edgeMap }
  }

  static identityOf (graph) {
    const nodeMap = {}
    const edgeMap = {}
    for (const n of Object.keys(graph.nodes)) nodeMap[n] = parseInt(n)
    for (const e of Object.keys(graph.edges)) edgeMap[e] = parseInt(e)
    return { nodeMap, edgeMap }
  }

  static isIdentity (m) {
    return Object.keys(m.nodeMap || {}).every((k) => String(m.nodeMap[k]) === k) &&
      Object.keys(m.edgeMap || {}).every((k) => String(m.edgeMap[k]) === k)
  }

  // every element of the group generated by the generators
  static closure (generators, identity) {
    const all = new Map()
    const queue = []
    const add = (m) => {
      const k = Base.key(m)
      if (!all.has(k)) {
        all.set(k, m)
        queue.push(m)
      }
    }
    add(identity)
    while (queue.length > 0) {
      const x = queue.shift()
      for (const g of generators) {
        add(Base.then(x, g))
        add(Base.then(g, x))
      }
    }
    return [...all.values()]
  }

  generateBase (morphisms) {
    this.base = []
    const all = morphisms.slice()
    const identity = all.find((m) => Base.isIdentity(m))
    if (identity === undefined) return
    let group = new Set([Base.key(identity)])
    this.saturation = [identity]
    // a morphism that the previous generators do not reach becomes a generator
    for (const m of all) {
      if (group.has(Base.key(m))) continue
      this.base.push(m)
      this.saturation = Base.closure(this.base, identity)
      group = new Set(this.saturation.map(Base.key))
    }
  }
}
module.exports = { Base }
